using Ookii.Dialogs.Wpf;
using System.Collections.Generic;
using System.Diagnostics;
using System.Globalization;
using System.IO;
using System.Threading;
using System.Windows;
using MangaToPdf.UIElements;
using System.Windows.Media;

namespace MangaToPdf
{
    /// <summary>
    /// Interaction logic for MainWindow.xaml
    /// </summary>
    public partial class MainWindow : Window
    {
        private string directoryZipPath = "";

        private class ProcessInfo
        {
            public Process Process { get; init; }
            public bool Finished { get; set; }
        }
        private Dictionary<string, Process> CurrentRunningProcessesDict = new();

        public MainWindow()
        {
            InitializeComponent();
            CultureInfo ci = new CultureInfo("en-US");
            Thread.CurrentThread.CurrentCulture = ci;
            Thread.CurrentThread.CurrentUICulture = ci;
            PathTextBox.Text = "No path is chosen";
            Closed += MainWindow_Closed;
        }

        private void MainWindow_Closed(object sender, System.EventArgs e)
        {
            foreach (Process process in CurrentRunningProcessesDict.Values)
            {
                process.Kill();
            }
        }

        private void ChooseDirButton_Click(object sender, RoutedEventArgs e)
        {
            VistaFolderBrowserDialog folderBrowserDialog = new();
            folderBrowserDialog.Multiselect = false;
            string path = Directory.GetCurrentDirectory();
            directoryZipPath = path;
            folderBrowserDialog.SelectedPath = path;
            if (folderBrowserDialog.ShowDialog() is null ? false : true)
            {
                path = folderBrowserDialog.SelectedPath;
                directoryZipPath = folderBrowserDialog.SelectedPath;
            }
            else
            {
                path = "No path is chosen";
            }
            PathTextBox.Text = path;
        }

        /// <summary>
        /// Converts all zip files in folder to PDF files.
        /// Zip files must be in format that is usually used by MangaLib.
        /// Resulting PDFs are stored in "zipFolderPath/output".
        /// </summary>
        /// <param name="zipFolderPath">Path to folder that contains zip files downloaded from MangaLib.</param>
        private void StartConversionAsync(string zipFolderPath, TaskListItem taskListItem)
        {
            Process process = new Process();
            lock (CurrentRunningProcessesDict)
            {
#if DEBUG
                process.StartInfo.FileName = @"..\..\..\py-env\Scripts\python.exe";
                process.StartInfo.ArgumentList.Add(@"..\..\..\python_executables\converter.py");
#else
                process.StartInfo.FileName = @"converter.exe";
#endif
                process.StartInfo.ArgumentList.Add(@"z");          // signal we want to use conversion from zip
                process.StartInfo.ArgumentList.Add(zipFolderPath); // path to folder with zips
                process.StartInfo.CreateNoWindow = true;           // We don't need new window
                process.StartInfo.UseShellExecute = false;         // Do not use OS shell
                process.StartInfo.RedirectStandardOutput = true;   // Any output, generated by application will be redirected back
                process.StartInfo.RedirectStandardError = true;    // Any error in standard output will be redirected back (for example exceptions)
                process.EnableRaisingEvents = true;                // Allow events, to handle process ending
                process.Exited += new System.EventHandler(
                    (object sender, System.EventArgs e) =>
                    {
                        lock (CurrentRunningProcessesDict)
                        {
                            if (CurrentRunningProcessesDict.ContainsKey(zipFolderPath))
                            {
                                Dispatcher.Invoke(new System.Action(() =>
                                {
                                    taskListItem.CancelButton.Background = Brushes.Green;
                                    taskListItem.CancelButton.Foreground = Brushes.White;
                                    taskListItem.CancelButton.Content = "Закрыть";
                                }));
                            }
                        }
                    });

                // Connect and setup UI Controller
                process.OutputDataReceived += (s, e) =>
                {
                    if (taskListItem is { })
                        taskListItem.PrintLogInfo(e.Data);
                };
                process.ErrorDataReceived += (s, e) =>
                {
                    if (taskListItem is { })
                        taskListItem.PrintLogInfo(e.Data);
                };
                taskListItem.CancelButton.Click += new RoutedEventHandler(
                    (object sender, RoutedEventArgs e) =>
                    {
                        lock (CurrentRunningProcessesDict)
                        {
                            if (CurrentRunningProcessesDict.ContainsKey(zipFolderPath))
                            {
                                MessageBoxResult result = MessageBox.Show("Отмена конвертации", "После отмены конвертацию нельзя будет продолжить с места остановки. При повторном запуске конвертацииобработка начнется с нуля. Продолжить?", MessageBoxButton.YesNo);
                                if (result != MessageBoxResult.Yes)
                                {
                                    return;
                                }
                                CurrentRunningProcessesDict[zipFolderPath].Kill();
                                CurrentRunningProcessesDict.Remove(zipFolderPath);
                            }
                            TaskListPanel.Children.Remove(taskListItem);
                        }
                    });

                CurrentRunningProcessesDict.Add(zipFolderPath, process);
            }

            process.Start();
            process.BeginOutputReadLine();
            process.BeginErrorReadLine();
        }

        private void ConvertToPdfButton_Click(object sender, RoutedEventArgs e)
        {
            if (CurrentRunningProcessesDict.ContainsKey(directoryZipPath))
            {
                MessageBox.Show("This manga is already being converted.");
                return;
            }
            TaskListItem taskListItem = new();
            TaskListPanel.Children.Add(taskListItem);
            new Thread(() => StartConversionAsync(directoryZipPath, taskListItem)).Start();
        }
    }
}